name: aml_project
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # Python
  - python=3.10

  # Data science
  - pandas=2.2.3
  - numpy=1.26.4
  - scipy=1.14.1
  - scikit-learn=1.5.2

  # Visualization
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - networkx=3.4.2

  # Dimensionality reduction
  - umap-learn=0.5.7

  # Jupyter
  - jupyter=1.1.1
  - ipykernel=6.29.5
  - notebook=7.2.2

  # Utilities
  - tqdm=4.66.5

# run pip install torch==2.6.0 torchvision==0.21.0 torchaudio==2.6.0 --index-url https://download.pytorch.org/whl/cu124
# then run pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.6.0+cu124.html
# finally run pip install torch_geometric

# if dataset needs to be downloaded run pip install kagglehub

# pip install xgboost